### ISSUE TITLE
ファイル貼り付け時のwsイベントの受け取り

### ISSUE THREAD

**Issue by Myoko1110** [Myoko1110/CraftSwitcher2-Client#4]
ファイル貼り付け時に、表示を更新するためにwsのイベントで貼り付け完了を受け取っているが、イベントの登録をする前にwsのイベントを受信してしまう。
どうやったら解決できるのだろうか。

**Comment by Myoko1110** [comment]
他のwsでイベントを受け取る処理も同様？

**Comment by Necnion8** [comment]
完了イベントはWSから常に受け取れますが、
copy, move, delete のリクエストは、処理が1秒以内に完了する場合はそれまでレスポンス返答を待機するようになっています。

時間がかからない短いファイルタスクはWSではなく、リクエストの返答でも完了を処理することで対応できると思います。

~~可能ならWSの通信は常に接続を維持したままにできるといいかもしれません。~~ => この件には関係なかったかも

**Comment by Myoko1110** [comment]
なるほど、有益な情報ありがとうございます。
レスポンスのresultが `success` ならそのまま更新、`pending` ならwsのイベントを受け取るような仕様にしたいと思います。

**Comment by Myoko1110** [comment]
> 可能ならWSの通信は常に接続を維持したままにできるといいかもしれません。

前にそのようなこと思ったんですよね。ログイン時にWSに接続するようにしてみます。

**Comment by Necnion8** [comment]
お願いします。こちら側の変更が必要だったら対応しますね。
