### ISSUE TITLE
サーバー設定のデフォルトの扱い

### ISSUE THREAD

**Issue by Myoko1110** [Myoko1110/CraftSwitcher2-Client#7]
サーバーの設定画面で、デフォルトの設定を適応出来るようにしたい。

**案1** 
入力がない場合はデフォルトの設定を適応
この場合だと、なにも設定したくない場合に不都合が生じる。

**案2**
一括でデフォルトの設定を適応するトグルを設置
この場合だと、個々で変えたい場合に不都合が生じる。

**案3**
個々の設定にデフォルトの設定を適応するトグルを設置
置いたとしても見た目が変になるし、なんかしつこい。

他になんかあるだろうか…

![Bh1XqRfcFZQAAAABJRU5ErkJggg](https://github.com/user-attachments/assets/bd54dd5c-1481-4f61-bb14-0b9c57a2479e)

**Comment by Necnion8** [comment]
こんな感じのトグルはどうですか？
ロック状態がグローバル設定であることがちょっと分かりにくい感じはありますが･･･

https://github.com/user-attachments/assets/ad046a31-7a8d-4515-86e1-4aaefe21e129

**Comment by Myoko1110** [comment]
わりと良いかもです
だけど、確かにアイコンがちょっと分かりにくいですね…
アイコン探してみます
